
version: '3'
services:
    python3_line:
     env_file: .env
     build:
       context: .
       args:
         UID: $UID
         GID: $GID
     container_name: 'python3_line'
     restart: always
     working_dir: '/opt/working'
     tty: true
     volumes:
        - ./working:/opt/working